### PR TITLE
Fix typo / link

### PR DESCRIPTION
**Pull request by stelfrich**
👍

### CODE REVIEW

**Comment by ctrueden** [comment]
Ach! I didn't see this before I fixed it myself in 36259538cddc0672f6a2ec1b20d5c8ffb5633a68. I merge anyway so you get joint credit for your efforts. :wink:

**Comment by stelfrich** [comment]
Would have been fine (for next time). I just know myself: notice errors during the talk and forget about them immediately afterwards. Plus, opening a PR was easier than filing an issue..

**Comment by ctrueden** [comment]
@stelfrich What would have been _fantastic_ is if you (or anyone) had filed a PR fixing the Ack slide, then raised your hand and told me before the talk was over, and then I live merged it and refreshed the page. Dude, that would have been such a powerful demonstration of the power of these collaboration tools.

**Comment by stelfrich** [comment]
I know! But I was actually following your talk and I find myself struggling with multi-tasking (really amazed by Dave's live-tweeting-fu)..

**Comment by ctrueden** [comment]
For sure—please understand my comment above for what it was: fantasizing, not criticism in any way! You rule, @stelfrich!

**Pull request merged**
